### PR TITLE
Add ability to set scope of the package.

### PR DESCRIPTION
**Pull request by grafov**
It should fix scope issues mentioned in #9. Code of `set-scope` adapted from go-guru project.

### CODE REVIEW

**Comment by microamp** [comment]
Thanks. I'll take a look at it more closely after work tonight. 👍

**Comment by microamp** [comment]
I have tried this version but I can still reproduce the error. Here's what I've done (in the following order),
```
$ mkdir $GOPATH/src/github.com/microamp/godoctor-example
$ cd $GOPATH/src/github.com/microamp/godoctor-example
$ touch main.go
```

main.go looks like below,
```go
package main

import "fmt"

func main() {
	num := 5
	fmt.Printf("num: %d\n", num)
}
```

Then within Emacs, `M-x godoctor-set-scope github.com/microamp/godoctor-example RET`, followed by `godoctor-rename` on `num` with the new name `n`. It works the first time, but trying to set `n` back to `num` raises the error as reported in #9.

**Comment by microamp** [comment]
@grafov 

Switching back and forth between `num` and a longer variable like `number` works fine. Maybe it's to do with a symbol's length, I'm not sure. I'll ask the godoctor team if they can reproduce it in Vim.

**Comment by grafov** [comment]
Ok, let dig further. Though I think scope setting feature would be useful anyway.

**Comment by microamp** [comment]
> Though I think scope setting feature would be useful anyway.

Right. Will take another quick look and merge it soon. Thanks again.

**Review by microamp — APPROVED** [review]

**Comment by microamp** [comment]
LGTM. Thanks for your contribution once again.

**Pull request merged**
